# feeder
feeder: st_gcn.feeder.Feeder
test_feeder_args:
  mode: test
  window_size: 150
  data_path: /home/justin/Documents/new-research/keypoint-new/new_format/gt/xview/train_data.npy
  label_path: /home/justin/Documents/new-research/keypoint-new/new_format/gt/xview/train_label.npy

# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 5
  channel: 2
  window_size: 150
  num_point: 25
  num_person: 1
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True 

# test 
phase: test
device: 0
test_batch_size: 1
weights: /home/justin/Documents/new-research/keypoint-new/st-gcn-data-len-master/work_dir/NTU-RGB-D/xview/ST_GCN/epoch80_model.pt



